name: Node.js Scan

on:
    push:
        branches: [master]
    pull_request:
        # The branches below must be a subset of the branches above
        branches: [master]
    schedule:
        - cron: "*/10 * * * *" # Every 10 minutes

jobs:
    njsscan:
        runs-on: ubuntu-latest
        name: njsscan code scanning
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            - name: nodejsscan scan
              id: njsscan
              uses: ajinabraham/njsscan-action@master
              with:
                  args: ". --sarif --output results.sarif || true"
            - name: Upload njsscan report
              uses: github/codeql-action/upload-sarif@v1
              with:
                  sarif_file: results.sarif
